updates to mac.

diff --git a/macdotfiles/aliases b/macdotfiles/aliases
--- a/macdotfiles/aliases
+++ b/macdotfiles/aliases
@@ -1,6 +1,7 @@
 #! /bin/sh
 
-### Aliases:
+### Aliases: ###
+
 alias las='ls -lAhgo'
 alias zsh='zsh --login'
 alias z='zsh --login'
@@ -8,25 +9,30 @@ alias cdd='pushd'
 alias cdb='popd'
 
 ## Mac Only ##
-alias eject_usb='diskutil unmount'
+alias eject-usb='diskutil unmount'
 alias java_home='/usr/libexec/java_home'
 alias macjs='/System/Library/Frameworks/JavaScriptCore.framework/Resources/jsc'
 alias delete='trash' #see function below
-alias hide-icons='hideIcons'
-alias show-icons='showIcons'
+alias hide-icons='hideIcons' #see function below
+alias show-icons='showIcons' #see function below
 alias visualvm='jvisualvm'
 
 ## Brew Related
 alias sha1='openssl sha1'
+alias sha256='openssl sha256'
 alias tmux-named='tmux new -s'
 
+## Homebrew Specific
 alias brew-uses='brew uses --installed'
 alias brew-requires='brew uses --installed'
 alias brew-deps='brew-dependencies' #Function Below
 alias brewbrew="brew update && brew upgrade && brew cleanup"
+alias bs="brew services"
 
-## Go Lang
-export PATH=$PATH:/usr/local/opt/go/libexec/bin
+## GO Lang
+if [ -e /usr/local/opt/go ]; then
+  export PATH=$PATH:/usr/local/opt/go/libexec/bin
+fi
 
 ## CoffeeScript
 alias coffee6='coffee --nodejs --harmony'
@@ -40,13 +46,16 @@ alias sg='shotgun -p 3000'
 alias sgp='shotgun -s puma -p 3000 config.ru'
 alias mrails='mjruby -S rails'
 alias rspec-init='bin/rails generate rspec:install'
-# if using rbenv instead of rvm I like below alias
+alias rbe='rbenv'
+# When using rbenv instead of rvm I like below alias
 alias rvm='rbenv'
+
 
 ## Python Related
 alias django-admin='django-admin.py'
 alias django-manage='python3 manage.py'
 alias pye='pyenv'
+alias p3='python3'
 
 ## ElasticSearch
 # alias els='elasticsearch'
@@ -66,11 +75,13 @@ alias pye='pyenv'
 
 
 
-### Applications:
+### Applications: ###
 
 ## For PostgresQL App
-alias psql="'/Applications/Postgres.app/Contents/Versions/latest/bin'/psql -p5432"
-export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin # needed for building gems
+if [ -e /Applications/Postgres.app ]; then
+  alias psql="'/Applications/Postgres.app/Contents/Versions/latest/bin'/psql -p5432"
+  export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin # needed for building gems
+fi
 
 ## JOSM
 if [ -e ~/Applications/JOSM.app ]; then
@@ -79,10 +90,12 @@ fi
 
 ## For other Mac Applications
 alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
-# alias safari='open -a Safari'
+alias safari-open='open -a Safari'
+alias opera='/Applications/Opera.app/Contents/MacOS/Opera'
 
 
-### Functions:
+### Functions: ###
+
 ## PostgresQL
 function pg(){
   # export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin;
@@ -96,6 +109,12 @@ function brew-dependencies(){
      brew deps $cask | awk '{printf(" %s ", $0)}'; echo "";
    done
  }
+ 
+ function brew-dependencies2(){
+    brew list | while read cask; do
+      brew deps --tree $cask;
+    done
+  }
 
 ## Dash
 function dashq(){
@@ -103,9 +122,12 @@ function dashq(){
 }
 
 ## ElasticSearch
+# if [ -e /usr/local/etc/elasticsearch/elasticsearch.yml ]; then
+# echo {{ brew services list | grep "elasticsearch" }}
 # function els_create_index(){
 #   curl -XPUT "localhost:9200/$1?pretty"
 # }
+# fi
 
 ## Atom Packages
 function setup_atom(){
@@ -113,6 +135,7 @@ function setup_atom(){
   apm install language-elm;
   apm install language-elixir;
   apm install elm-format;
+  #elm beautify
   apm install file-icons;
   apm install mini-map;
   apm install minimap-highlight-selected;
@@ -150,23 +173,48 @@ fi
 # jre/lib/security
 
 
-### Experimental
+### Experimental ###
 if (ls /Applications | grep -q 'Julia'); then
   # mac only (location)
-  alias julia="/Applications/${$(ls /Applications | grep 'Julia'| head -1)}/Contents/Resources/julia/bin/julia"
+  # alias julia="/Applications/\"${$(ls /Applications | grep 'Julia')}\"/Contents/Resources/julia/bin/julia";
+  alias julia="/Applications/\"$(ls /Applications | grep 'Julia' | head -1)\"/Contents/Resources/julia/bin/julia";
 fi
 
 if (ls /Applications | grep -q 'Firefox'); then
-  # mac only (location)
-    alias firefox="/Applications/\"${$(ls /Applications | grep 'Firefox' | head -1)}\"/Contents/MacOS/firefox";
+  # For Firefox Development Edition (mac only)
+  # alias firefox="/Applications/\"${$(ls /Applications | grep 'Firefox')}\"/Contents/MacOS/firefox";
+  alias firefox="/Applications/\"$(ls /Applications | grep 'Firefox' | head -1)\"/Contents/MacOS/firefox";
 fi
 
-if (command -v pygmentize >/dev/null 2>&1 || exit 1 ); then 
-  ## command -v <command>, type and hash are cheaper and quiter than `which'
-  ## command -v foo >/dev/null 2>&1 || { echo >&2 "aborting"; exit 1; }
-  ## type foo >/dev/null 2>&1 || exit 1 ## hash foo 2>/dev/null || exit 1
-  alias pcat='pygmentize -f terminal256 -O style=monokai -g'
+# if (command -v pygmentize >/dev/null 2>&1 || exit 1 ); then
+#   ## command -v <command>, type and hash are cheaper and quiter than `which'
+#   ## command -v foo >/dev/null 2>&1 || { echo >&2 "aborting"; exit 1; }
+#   ## type foo >/dev/null 2>&1 || exit 1
+#   ## hash foo 2>/dev/null || exit 1
+#   ## pip3 install Pygments
+#   ## Make alias anyway as pyenv has trouble w/ pip
+# fi
+alias pcat='pygmentize -f terminal256 -O style=monokai -g'
+
+
+if (ls $HOME/.jars/ | grep -q 'plantuml'); then
+  function plantuml(){
+    # Install the plantuml jar in a a folder called .jars on your home.
+    java -jar $HOME/.jars/$(ls $HOME/.jars/ | grep 'plantuml' | head -1) $1
+  }
 fi
+
+function minify(){
+  # yuicompressor --disable-optimizations $1 -o $2
+  # uglify-js is a npm package that should be installed globally `npm install uglify-js --global`
+  uglifyjs $1 --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output $2
+}
+
+# if (type closure-compiler >/dev/null 2>&1 || exit 1); then
+#   function minifyjs(){
+#     closure-compiler --js $1 --js_output_file $2
+#   }
+# fi
 
 function elm-heroku(){
   # maybe add an h2o server start on this.
@@ -181,4 +229,9 @@ function port-uses() {
 function invert-colors() {
   # mac only
   echo "Go to 'System Preferences>Keyboard>Keyboard shortcuts>Accessibility' and turn on the keyboard shortcut."
+}
+
+function disable-swipe-naviation() {
+  defaults write com.operasoftware.Opera AppleEnableSwipeNavigateWithScrolls -bool FALSE
+  defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE
 }
